-- SCHUTZ-APP V28 — FIX STABLE BOUTIQUE / COMMANDES / AVIS
-- À exécuter APRÈS SUPABASE_SCHUTZ_V28_COMPLETE.sql
-- Ce patch corrige surtout les RPC client et active le temps réel.
BEGIN;

-- 1) RPC commandes client : lecture uniquement des commandes du compte connecté
DROP FUNCTION IF EXISTS public.get_my_shop_orders();
CREATE OR REPLACE FUNCTION public.get_my_shop_orders()
RETURNS SETOF public.shop_orders
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT o.*
  FROM public.shop_orders AS o
  WHERE o.user_id = auth.uid()
  ORDER BY o.created_at DESC;
$$;
GRANT EXECUTE ON FUNCTION public.get_my_shop_orders() TO authenticated;

-- 2) Historique client
DROP FUNCTION IF EXISTS public.get_my_order_history(uuid);
CREATE OR REPLACE FUNCTION public.get_my_order_history(p_order_id uuid)
RETURNS TABLE(status text, created_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.status, h.created_at
  FROM public.shop_order_history AS h
  JOIN public.shop_orders AS o ON o.id = h.order_id
  WHERE h.order_id = p_order_id
    AND o.user_id = auth.uid()
  ORDER BY h.created_at DESC;
$$;
GRANT EXECUTE ON FUNCTION public.get_my_order_history(uuid) TO authenticated;

-- 3) Table des avis si elle n'existe pas encore
CREATE TABLE IF NOT EXISTS public.shop_order_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL UNIQUE REFERENCES public.shop_orders(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pseudo text NOT NULL DEFAULT 'Client',
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.shop_order_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shop_order_reviews_public_select" ON public.shop_order_reviews;
CREATE POLICY "shop_order_reviews_public_select"
ON public.shop_order_reviews
FOR SELECT TO anon, authenticated
USING (true);

-- 4) Avis public : cette fonction ne dépend d'aucune donnée de profil
DROP FUNCTION IF EXISTS public.get_public_shop_reviews();
CREATE OR REPLACE FUNCTION public.get_public_shop_reviews()
RETURNS TABLE(rating integer, comment text, pseudo text, created_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT r.rating, r.comment, r.pseudo, r.created_at
  FROM public.shop_order_reviews AS r
  ORDER BY r.created_at DESC
  LIMIT 50;
$$;
GRANT EXECUTE ON FUNCTION public.get_public_shop_reviews() TO anon, authenticated;

-- 5) Avis de la commande du client
DROP FUNCTION IF EXISTS public.get_my_order_review(uuid);
CREATE OR REPLACE FUNCTION public.get_my_order_review(p_order_id uuid)
RETURNS TABLE(rating integer, comment text, pseudo text, created_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT r.rating, r.comment, r.pseudo, r.created_at
  FROM public.shop_order_reviews AS r
  JOIN public.shop_orders AS o ON o.id = r.order_id
  WHERE r.order_id = p_order_id
    AND o.user_id = auth.uid()
  LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.get_my_order_review(uuid) TO authenticated;

-- 6) Publier/modifier un avis.
-- Le pseudo vient de la commande : aucune dépendance obligatoire à player_data.
DROP FUNCTION IF EXISTS public.submit_my_order_review(uuid, integer, text);
CREATE OR REPLACE FUNCTION public.submit_my_order_review(
  p_order_id uuid,
  p_rating integer,
  p_comment text
)
RETURNS public.shop_order_reviews
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_order public.shop_orders;
  v_review public.shop_order_reviews;
  v_pseudo text;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Utilisateur non connecté';
  END IF;

  IF p_rating IS NULL OR p_rating < 1 OR p_rating > 5 THEN
    RAISE EXCEPTION 'Note invalide';
  END IF;

  SELECT *
  INTO v_order
  FROM public.shop_orders
  WHERE id = p_order_id
    AND user_id = v_user;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Commande introuvable ou non autorisée';
  END IF;

  IF v_order.status <> 'delivered' THEN
    RAISE EXCEPTION 'La commande doit être livrée avant de pouvoir être notée';
  END IF;

  v_pseudo := COALESCE(
    NULLIF(left(btrim(v_order.pseudo), 32), ''),
    'Client'
  );

  INSERT INTO public.shop_order_reviews(
    order_id, user_id, pseudo, rating, comment, updated_at
  )
  VALUES(
    p_order_id,
    v_user,
    v_pseudo,
    p_rating,
    COALESCE(left(p_comment, 2000), ''),
    now()
  )
  ON CONFLICT (order_id)
  DO UPDATE SET
    rating = EXCLUDED.rating,
    comment = EXCLUDED.comment,
    pseudo = EXCLUDED.pseudo,
    updated_at = now()
  RETURNING * INTO v_review;

  RETURN v_review;
END;
$$;
GRANT EXECUTE ON FUNCTION public.submit_my_order_review(uuid, integer, text) TO authenticated;

-- 7) Historique : s'assurer que chaque commande possède au moins son statut initial.
CREATE TABLE IF NOT EXISTS public.shop_order_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES public.shop_orders(id) ON DELETE CASCADE,
  status text NOT NULL,
  changed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS shop_order_history_order_id_idx
  ON public.shop_order_history(order_id, created_at DESC);

ALTER TABLE public.shop_order_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shop_order_history_select_own" ON public.shop_order_history;
CREATE POLICY "shop_order_history_select_own"
ON public.shop_order_history FOR SELECT TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.shop_orders o
    WHERE o.id = shop_order_history.order_id
      AND o.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "shop_order_history_select_staff" ON public.shop_order_history;
CREATE POLICY "shop_order_history_select_staff"
ON public.shop_order_history FOR SELECT TO authenticated
USING (public.is_shop_staff());

CREATE OR REPLACE FUNCTION public.record_shop_order_history()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.shop_order_history(order_id, status, changed_by)
    VALUES (NEW.id, NEW.status, auth.uid());
  ELSIF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.shop_order_history(order_id, status, changed_by)
    VALUES (NEW.id, NEW.status, auth.uid());
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_shop_order_history ON public.shop_orders;
CREATE TRIGGER trg_shop_order_history
AFTER INSERT OR UPDATE OF status ON public.shop_orders
FOR EACH ROW EXECUTE FUNCTION public.record_shop_order_history();

INSERT INTO public.shop_order_history(order_id, status, changed_by, created_at)
SELECT o.id, o.status, NULL, COALESCE(o.updated_at, o.created_at, now())
FROM public.shop_orders o
WHERE NOT EXISTS (
  SELECT 1 FROM public.shop_order_history h
  WHERE h.order_id = o.id
);

-- 8) Temps réel Supabase pour les commandes.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
  ) THEN
    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'shop_orders'
    ) THEN
      EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.shop_orders';
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime'
        AND schemaname = 'public'
        AND tablename = 'shop_order_history'
    ) THEN
      EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.shop_order_history';
    END IF;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
COMMIT;
