-- ============================================================
-- SCHUTZ APP V26+ — SUIVI COMMANDES / HISTORIQUE / AVIS
-- À copier-coller dans Supabase SQL Editor
-- ============================================================

-- 1) Historique des commandes
CREATE TABLE IF NOT EXISTS public.shop_order_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES public.shop_orders(id) ON DELETE CASCADE,
  status text NOT NULL,
  changed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS shop_order_history_order_id_idx
ON public.shop_order_history(order_id, created_at DESC);

ALTER TABLE public.shop_order_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shop_order_history_select_own" ON public.shop_order_history;
DROP POLICY IF EXISTS "shop_order_history_select_staff" ON public.shop_order_history;

CREATE POLICY "shop_order_history_select_own"
ON public.shop_order_history
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.shop_orders o
    WHERE o.id = shop_order_history.order_id
      AND o.user_id = auth.uid()
  )
);

CREATE POLICY "shop_order_history_select_staff"
ON public.shop_order_history
FOR SELECT
TO authenticated
USING (
  public.is_shop_staff()
);

-- 2) Historique automatique à la création / modification du statut
CREATE OR REPLACE FUNCTION public.record_shop_order_history()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.shop_order_history(order_id,status,changed_by)
    VALUES (NEW.id, NEW.status, auth.uid());
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' AND NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO public.shop_order_history(order_id,status,changed_by)
    VALUES (NEW.id, NEW.status, auth.uid());
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_shop_order_history
ON public.shop_orders;

CREATE TRIGGER trg_shop_order_history
AFTER INSERT OR UPDATE OF status
ON public.shop_orders
FOR EACH ROW
EXECUTE FUNCTION public.record_shop_order_history();

-- 3) Reconstituer l'historique minimal des anciennes commandes
INSERT INTO public.shop_order_history(order_id,status,changed_by,created_at)
SELECT o.id, o.status, NULL, COALESCE(o.updated_at,o.created_at,now())
FROM public.shop_orders o
WHERE NOT EXISTS (
  SELECT 1
  FROM public.shop_order_history h
  WHERE h.order_id = o.id
);

-- 4) Avis clients
CREATE TABLE IF NOT EXISTS public.shop_order_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL UNIQUE REFERENCES public.shop_orders(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pseudo text NOT NULL DEFAULT 'Client',
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS shop_order_reviews_created_at_idx
ON public.shop_order_reviews(created_at DESC);

ALTER TABLE public.shop_order_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "shop_order_reviews_public_select" ON public.shop_order_reviews;
DROP POLICY IF EXISTS "shop_order_reviews_insert_own" ON public.shop_order_reviews;
DROP POLICY IF EXISTS "shop_order_reviews_update_own" ON public.shop_order_reviews;
DROP POLICY IF EXISTS "shop_order_reviews_delete_own" ON public.shop_order_reviews;

CREATE POLICY "shop_order_reviews_public_select"
ON public.shop_order_reviews
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "shop_order_reviews_insert_own"
ON public.shop_order_reviews
FOR INSERT
TO authenticated
WITH CHECK (
  user_id = auth.uid()
  AND EXISTS (
    SELECT 1
    FROM public.shop_orders o
    WHERE o.id = shop_order_reviews.order_id
      AND o.user_id = auth.uid()
      AND o.status = 'delivered'
  )
);

CREATE POLICY "shop_order_reviews_update_own"
ON public.shop_order_reviews
FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

CREATE POLICY "shop_order_reviews_delete_own"
ON public.shop_order_reviews
FOR DELETE
TO authenticated
USING (user_id = auth.uid());

-- 5) Empêcher un avis sur une commande qui n'est pas livrée
CREATE OR REPLACE FUNCTION public.check_shop_order_review()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_status text;
  v_user uuid;
BEGIN
  SELECT status,user_id
  INTO v_status,v_user
  FROM public.shop_orders
  WHERE id = NEW.order_id;

  IF v_status IS DISTINCT FROM 'delivered' THEN
    RAISE EXCEPTION 'Une commande doit être livrée avant de pouvoir être notée';
  END IF;

  IF v_user IS DISTINCT FROM NEW.user_id THEN
    RAISE EXCEPTION 'Cette commande ne vous appartient pas';
  END IF;

  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_check_shop_order_review
ON public.shop_order_reviews;

CREATE TRIGGER trg_check_shop_order_review
BEFORE INSERT OR UPDATE
ON public.shop_order_reviews
FOR EACH ROW
EXECUTE FUNCTION public.check_shop_order_review();

-- 6) La modification du statut admin reste compatible et l'historique
--    est maintenant ajouté automatiquement par le trigger.
DROP FUNCTION IF EXISTS public.admin_update_order_status(uuid,text);

CREATE OR REPLACE FUNCTION public.admin_update_order_status(
  p_order_id uuid,
  p_status text
)
RETURNS public.shop_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.shop_orders;
BEGIN
  IF NOT public.is_shop_staff() THEN
    RAISE EXCEPTION 'Accès réservé au staff';
  END IF;

  IF p_status NOT IN (
    'awaiting_payment',
    'paid',
    'preparing',
    'shipped',
    'delivered',
    'cancelled'
  ) THEN
    RAISE EXCEPTION 'Statut de commande invalide';
  END IF;

  UPDATE public.shop_orders
  SET status = p_status,
      updated_at = now()
  WHERE id = p_order_id
  RETURNING * INTO v_order;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Commande introuvable';
  END IF;

  RETURN v_order;
END;
$$;

GRANT EXECUTE
ON FUNCTION public.admin_update_order_status(uuid,text)
TO authenticated;

-- 7) Rafraîchir PostgREST
NOTIFY pgrst, 'reload schema';

-- ============================================================
-- FIN
-- ============================================================
